- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Show ENV Vars 
      debug:
        msg: "{{ lookup('env', 'HOME')}}"
    - name: Create Directories
      debug:
      file:
        path: " {{ item }} "
        state: directory
        with_items:
        - /home/sandboxadmin/ansiblePOC/folder1
        - /home/sandboxadmin/ansiblePOC/folder2
        - /home/sandboxadmin/ansiblePOC/folder3
        recurse: yes
        mode: 0755

