- name: Hello World Sample
  hosts: all
  
  vars_files:
    - ./group_vars/ssh/varibales.yml
    - ./group_vars/ssh/vaultFile.yaml
    
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Show ENV Vars 
      debug:
        msg: "{{ lookup('env', 'HOME')}}"
    - name: Create Directories
      file:
        path: '/home/sandboxadmin/ansiblePOC/folder1'
        state: directory
        recurse: yes
        mode: 0755

    - name: Create new user using passworrd from vault variable
      shell: useradd ansiuser4 &&  echo {{ vault_sshpassword }} | passwd ansiuser4 --stdin
