- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"tasks:
    - name: Show ENV Vars 
      debug:
        msg: "{{ lookup('env', 'HOME')}}"
