- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Show ENV Vars 
      debug:
        msg: "{{ lookup('env', 'HOME')}}"
    - name: Create Directories
      file:
        path: '/home/sandboxadmin/ansiblePOC/folder1'
        state: directory
        recurse: yes
        mode: 0755
